name: EnchantShopX
main: NurAzli\EnchantShopX\Main.php
version: 1.0.0
api: 5.0.0
author: 
- NurAzli

commands:
   eshop:
     description: "Open enchant shop menu"
     permission: eshopx.cmd

permissions:
  eshopx.cmd:
    default: true
